#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/opt/conda/envs/bladder_model"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/opt/conda/envs/bladder_model/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/jovyan/work/neuralnetwork/code/x86_64/.libs/libnrnmech.so" "$@"
